"""Build Aurora's seed visual style library."""

from __future__ import annotations

from project_aurora.style_intelligence.style_profile import StyleProfile


class StyleLibraryBuilder:
    """Create production-ready broad style-family profiles."""

    def build_seed_library(self) -> tuple[StyleProfile, ...]:
        """Return Aurora's initial style profile library."""
        return (
            _style(
                "storybook_watercolor",
                "Storybook Watercolor",
                (
                    "Soft illustrated storybook style for cheerful printable "
                    "collections with gentle character appeal."
                ),
                ("storybook charm", "watercolor softness", "friendly details"),
                ("cream", "blush pink", "sage", "warm yellow", "berry red"),
                "soft watercolor washes with delicate layered details",
                "gentle clean outlines with hand-drawn variation",
                "warm natural light with soft highlights",
                "centered hero artwork with balanced supporting motifs",
                "paper grain and translucent watercolor blooms",
                ("party printable", "clipart", "sticker sheet"),
                ("Spring", "Summer", "Evergreen"),
                ("parents", "teachers", "digital printable buyers"),
                0.96,
            ),
            _style(
                "cottagecore_watercolor",
                "Cottagecore Watercolor",
                "Garden-led watercolor style with cozy handmade charm.",
                ("wildflowers", "garden textures", "pastoral sweetness"),
                ("sage", "cream", "dusty rose", "mushroom beige"),
                "loose botanical watercolor strokes",
                "soft pencil-like contour lines",
                "dappled golden-hour light",
                "clusters, borders, and gentle organic spacing",
                "subtle handmade paper texture",
                ("digital paper", "clipart", "junk journal"),
                ("Spring", "Summer", "Evergreen"),
                ("crafters", "printable buyers"),
                0.93,
            ),
            _style(
                "vintage_botanical",
                "Vintage Botanical",
                "Classic botanical printable style with aged reference charm.",
                ("pressed florals", "engraved details", "heirloom layout"),
                ("ivory", "olive", "sepia", "muted rose"),
                "controlled washes with botanical shading",
                "fine engraved linework",
                "muted archival lighting",
                "specimen layout, labels avoided, balanced negative space",
                "aged paper and fine ink texture",
                ("wall art", "junk journal", "digital paper"),
                ("Spring", "Evergreen"),
                ("crafters", "teachers"),
                0.9,
            ),
            _style(
                "cute_farm_animals",
                "Cute Farm Animals",
                "Playful farm animal style for child-friendly printable sets.",
                ("round animals", "friendly faces", "simple props"),
                ("cream", "sky blue", "butter yellow", "barn red"),
                "smooth watercolor with soft fills",
                "rounded clean outlines",
                "bright cheerful daylight",
                "individual character poses and printable groupings",
                "soft paper texture",
                ("clipart", "sticker sheet", "party printable"),
                ("Spring", "Evergreen"),
                ("parents", "teachers"),
                0.89,
            ),
            _style(
                "woodland_friends",
                "Woodland Friends",
                "Sweet woodland character family style for cozy collections.",
                ("forest animals", "mushrooms", "leafy accents"),
                ("moss green", "acorn brown", "cream", "soft orange"),
                "warm watercolor with layered washes",
                "gentle storybook contour lines",
                "filtered woodland light",
                "scenic clusters and centered character scenes",
                "watercolor paper and soft shadow texture",
                ("clipart", "nursery wall art", "sticker sheet"),
                ("Fall", "Spring", "Evergreen"),
                ("parents", "digital printable buyers"),
                0.91,
            ),
            _style(
                "cozy_autumn",
                "Cozy Autumn",
                "Warm fall printable style with soft seasonal comfort.",
                ("pumpkins", "leaves", "cozy textures"),
                ("pumpkin", "cinnamon", "cream", "dusty green"),
                "rich watercolor washes",
                "soft rustic linework",
                "warm amber light",
                "border layouts, clusters, and seasonal frames",
                "grainy paper and soft shadow texture",
                ("wall art", "digital paper", "party printable"),
                ("Fall",),
                ("crafters", "parents"),
                0.88,
            ),
            _style(
                "vintage_christmas",
                "Vintage Christmas",
                "Nostalgic holiday style with warm traditional charm.",
                ("ornaments", "ribbons", "evergreen sprigs"),
                ("cranberry", "pine", "cream", "antique gold"),
                "vintage watercolor and gouache-inspired details",
                "classic soft ink outlines",
                "glowing holiday light",
                "frames, borders, tags, and card-ready compositions",
                "aged paper with subtle festive grain",
                ("gift tags", "wall art", "digital paper"),
                ("Winter", "Christmas"),
                ("crafters", "digital printable buyers"),
                0.9,
            ),
            _style(
                "soft_nursery",
                "Soft Nursery",
                "Gentle nursery style for calm child-focused printables.",
                ("rounded motifs", "sleepy shapes", "soft icons"),
                ("pastel blue", "blush", "cream", "warm gray"),
                "very soft watercolor gradients",
                "minimal gentle linework",
                "diffused nursery light",
                "centered wall-art and balanced pattern layouts",
                "smooth matte paper softness",
                ("wall art", "digital paper", "clipart"),
                ("Evergreen", "Spring"),
                ("parents", "teachers"),
                0.87,
            ),
            _style(
                "fairy_garden",
                "Fairy Garden",
                "Whimsical fantasy garden style with magical printable appeal.",
                ("fairy cottages", "flowers", "sparkles", "tiny doors"),
                ("lavender", "sage", "butter yellow", "rose"),
                "luminous watercolor with tiny detail accents",
                "delicate storybook linework",
                "glowing garden light",
                "scene vignettes and magical corner clusters",
                "soft paper grain with sparkle-like highlights",
                ("clipart", "party printable", "sticker sheet"),
                ("Spring", "Summer"),
                ("parents", "crafters"),
                0.92,
            ),
            _style(
                "strawberry_summer",
                "Strawberry Summer",
                "Bright berry-led summer style for party and printable bundles.",
                ("strawberries", "gingham", "flowers", "ribbons"),
                ("berry red", "blush pink", "cream", "sage", "warm yellow"),
                "fresh watercolor with crisp decorative accents",
                "clean sweet outlines with playful detail",
                "sunny warm summer light",
                "centered hero motifs, patterns, and party-ready clusters",
                "clean printable texture with gentle watercolor bloom",
                ("party printable", "digital paper", "clipart"),
                ("Summer",),
                ("parents", "digital printable buyers"),
                0.95,
            ),
        )


def _style(
    style_id: str,
    style_name: str,
    description: str,
    visual_characteristics: tuple[str, ...],
    color_palette: tuple[str, ...],
    brush_style: str,
    line_style: str,
    lighting: str,
    composition: str,
    texture: str,
    recommended_products: tuple[str, ...],
    recommended_seasons: tuple[str, ...],
    recommended_audiences: tuple[str, ...],
    confidence: float,
) -> StyleProfile:
    return StyleProfile(
        style_id=style_id,
        style_name=style_name,
        description=description,
        visual_characteristics=visual_characteristics,
        color_palette=color_palette,
        brush_style=brush_style,
        line_style=line_style,
        lighting=lighting,
        composition=composition,
        texture=texture,
        recommended_products=recommended_products,
        recommended_seasons=recommended_seasons,
        recommended_audiences=recommended_audiences,
        confidence=confidence,
    )
